language: java
branches:
  only:
  - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lftp
script:
  - mvn clean deploy --settings .maven.settings
  - lftp sftp://$UPLOADER_USER:$UPLOADER_PASSWORD@$UPLOADER_HOST -e "mkdir -f uploads/box2dlights; mput target/*.jar -O uploads/box2dlights; bye"